# Generated by Django 3.2.18 on 2023-04-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='date_of_birth',
            field=models.DateTimeField(),
        ),
    ]
