# Generated by Django 3.2.18 on 2023-04-19 00:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_students_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='chemistry_marks',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='students',
            name='computer_science_marks',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='students',
            name='maths_marks',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='students',
            name='physics_marks',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
